NHSDigital/booking-and-referral-fhir-api

azure/azure-release-pipeline.yml
=> AMB-809 fix release pipeline definitions

azure/templates/run-tests.yml
=> AMB-809 change service name

proxies/live/apiproxy/policies/KeyValueMapOperations.GetBookingAndReferralConfig.xml, proxies/live/apiproxy/policies/ServiceCallout.GetTargetsKvm.xml, proxies/live/apiproxy/resources/jsc/BarsLibrary.js, proxies/live/apiproxy/resources/jsc/SetTargetUrl.js, proxies/live/apiproxy/resources/jsc/UnpackVars.js, proxies/live/apiproxy/targets/bref-target.xml
=> AMB-833 create service callout to retrieve kvm from github

proxies/live/apiproxy/resources/jsc/BarsLibrary.js, tests/conftest.py, tests/test_endpoints.py
=> AMB-833 clean backslash from url

tests/test_endpoints.py
=> AMB-833 template environment in test

specification/examples/service_request/GET-success.json, specification/examples/service_request/id/GET-success.json, specification/examples/service_request/id/PATCH-success.json, specification/examples/service_request/id/PUT-success.json, tests/pytest.ini, tests/test_appointment.py, tests/test_service_request.py
=> AMB-815 add /ServiceRequest endpoint

specification/examples/process_message/POST-success.json, tests/pytest.ini, tests/test_process_message.py
=> AMB-836 add /$process-message endpoint

azure/templates/run-tests.yml, poetry.lock, proxies/live/apiproxy/targets/bref-target.xml, pyproject.toml, specification/examples/document_reference/GET-success.json, specification/examples/document_reference/POST-body.json, specification/examples/document_reference/id/GET-success.json, specification/examples/document_reference/id/PUT-body.json, tests/configuration/environment.py, tests/conftest.py, tests/example_loader.py, tests/test_appointment.py, tests/test_document_reference.py, tests/test_endpoints.py
Add DocumentReference endpoint and tests...
=> AMB-841 add DocumentReference endpoint with tests

tests/test_slots.py
=> AMB-827 rename test class

proxies/live/apiproxy/policies/AssignMessage.Tagets.xml, proxies/live/apiproxy/policies/LookupCache.Targets.xml, proxies/live/apiproxy/policies/PopulateCache.Targets.xml, proxies/live/apiproxy/policies/ServiceCallout.GetTargetsKvm.xml, proxies/live/apiproxy/resources/jsc/UnpackVars.js, proxies/live/apiproxy/targets/bref-target.xml
Cache the json object containing the targets urls 
=> AMB-821 Add cache

sandbox/src/main.py, tests/conftest.py
=> AMB-816 add all internal envs to conftest

azure/azure-release-pipeline.yml
=> AMB-844 Added flag to enable internal_qa_sandbox

azure/templates/run-tests.yml
=> AMB-816 exclude broker mark tests

tests/api_test.py, tests/conftest.py, tests/pytest.ini
=> Amb 816 return fake access token for sandbox envs

specification/booking-and-referral.yaml
=> Changes implemented as per latest file

CODEOWNERS
=> AMB-854 Add Codeowners to repo

proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml, specification/booking-and-referral.yaml
=> AMB-863 Fix try this API feature

specification/booking-and-referral.yaml
=> AMB-906 use previous service identifier in spec

azure/project.yml, proxies/live/apiproxy/policies/AssignMessage.Targets.xml, proxies/live/apiproxy/policies/PopulateCache.Targets.xml, specification/booking-and-referral.yaml
=> AMB-910 add /FHIR/R4 to proxy's base path

proxies/live/apiproxy/policies/Javascript.CheckTargets.xml, proxies/live/apiproxy/resources/jsc/CheckTargets.js, proxies/live/apiproxy/targets/bref-target.xml
create new js policy to checks targets
=> AMB-960 - create new js policy to check targets

specification/booking-and-referral.yaml
=> AMB-963 Spec improvements

specification/booking-and-referral.yaml
=> AMB-994 fix spec wording

.flake8, proxies/live/apiproxy/policies/Javascript.DecodeBase64.xml, proxies/live/apiproxy/policies/Python.DecodeBase64.xml, proxies/live/apiproxy/resources/jsc/BarsLibrary.js, proxies/live/apiproxy/resources/jsc/CheckTargets.js, proxies/live/apiproxy/resources/jsc/DecodeBase64String.js, proxies/live/apiproxy/resources/jsc/SetTargetUrl.js, proxies/live/apiproxy/resources/py/DecodeBase64String.py, proxies/live/apiproxy/targets/bref-target.xml, sandbox/src/routes/appointment.py, sandbox/src/routes/message_definition.py, sandbox/src/routes/metadata.py, sandbox/src/routes/process_message.py, sandbox/src/routes/service_request.py, sandbox/src/routes/slots.py, tests/test_appointment.py, tests/test_document_reference.py, tests/test_endpoints.py, tests/test_message_definition.py, tests/test_metadata.py, tests/test_process_message.py, tests/test_receiver_errors.py, tests/test_service_request.py, tests/test_slots.py
=> AMB-1043 Update ServiceID header format

sandbox/src/routes/slots.py, tests/test_appointment.py, tests/test_document_reference.py, tests/test_endpoints.py, tests/test_message_definition.py, tests/test_metadata.py, tests/test_process_message.py, tests/test_receiver_errors.py, tests/test_service_request.py, tests/test_slots.py
=> AMB-1045 update with new headers and params

mock-receiver/debug/index.js, terraform/.gitignore, terraform/.terraform.lock.hcl, terraform/Makefile, terraform/api.tf, terraform/api.yaml, terraform/bucket.tf, terraform/lambda.tf, terraform/main.tf, terraform/route53.tf, terraform/var.tf
=> Amb 1056 add apigateway and lambda

mock-receiver/debug/index.js, sandbox/Dockerfile, terraform/.gitignore, terraform/.terraform.lock.hcl, terraform/Makefile, terraform/api.tf, terraform/api.yaml, terraform/bucket.tf, terraform/ecr.tf, terraform/lambda.tf, terraform/main.tf, terraform/route53.tf, terraform/var.tf
=> Amb 1098 run sandbox container in lambda

mock-receiver/app.py
=> Amb 1102 add remaining mock receiver endpoints

.flake8, mock-receiver/app.py, proxies/live/apiproxy/resources/jsc/BarsLibrary.js, proxies/live/apiproxy/resources/jsc/CheckTargets.js, proxies/live/apiproxy/resources/jsc/SetTargetUrl.js, proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml, sandbox/src/routes/appointment.py, sandbox/src/routes/errors.py, sandbox/src/routes/message_definition.py, sandbox/src/routes/metadata.py, sandbox/src/routes/process_message.py, sandbox/src/routes/service_request.py, sandbox/src/routes/slots.py, tests/test_appointment.py, tests/test_document_reference.py, tests/test_endpoints.py, tests/test_message_definition.py, tests/test_metadata.py, tests/test_process_message.py, tests/test_receiver_errors.py, tests/test_service_request.py, tests/test_slots.py
=> AMB-1048-RemovalOfNhsdServiceHeader

proxies/live/apiproxy/targets/bref-target.xml, terraform/api.tf
=> AMB-1053 - TLS-CERTS

proxies/live/apiproxy/targets/bref-target.xml
=> AMB-1053 revert ssl to old certs

README.md, tests/README.md
=> updated README files

azure/azure-release-pipeline.yml, manifest_template.yml
=> Amb 1197 add prod deployment

specification/booking-and-referral.yaml, specification/examples/message_definition/MessageDefinition_ServiceRequest-request_CaseTransfer.json, specification/schemas/MessageDefinition.yaml
* Spec param changes for GET /Slots
* changes to some example responses.
=> Amb 9992 slot endpoint revisions

proxies/live/apiproxy/policies/AssignMessage.404ProxyNotFoundErrorResponse.xml, proxies/live/apiproxy/targets/bref-target.xml, specification/examples/proxy-not-found.json, tests/test_endpoints.py
=> AMB-1230: Added OperationalOutcome response for Proxy404 Fault

proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml
=> AMB-000 update AddCors policy to allow headers

proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml
=> AMB-000 add remaining headers to Add Cors policy

proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml
=> AMB-000 add headers to expose in AddCors policy

sandbox/src/main.py
=> AMB-1278 add CORS middleware to FastAPI App

proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml, sandbox/src/main.py, sandbox/src/routes/appointment.py, sandbox/src/routes/message_definition.py, sandbox/src/routes/metadata.py, sandbox/src/routes/process_message.py, sandbox/src/routes/service_request.py, sandbox/src/routes/slots.py, tests/test_appointment.py, tests/test_process_message.py, tests/test_receiver_errors.py, tests/test_service_request.py, tests/test_slots.py
=> AMB-1278 update required headers in sandbox

sandbox/src/routes/appointment.py, sandbox/src/routes/service_request.py, sandbox/src/routes/slots.py, tests/test_appointment.py, tests/test_service_request.py
=> AMB-1278 update patient:identifier query param

sandbox/src/routes/slots.py
=> AMB-1278 remove no longer required HealthcareService query from Slots.py

specification/booking-and-referral.yaml
See https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#status
=> Change alpha-to-in-development

Makefile, proxies/live/apiproxy/policies/AssignMessage.400InvalidBase64Encoding.xml, proxies/live/apiproxy/policies/AssignMessage.400InvalidTargetIdentifierValue.xml, proxies/live/apiproxy/policies/RaiseFault.400MalformedTargetIdentifier.xml, proxies/live/apiproxy/resources/jsc/CheckTargets.js, proxies/live/apiproxy/resources/py/DecodeBase64String.py, proxies/live/apiproxy/targets/bref-target.xml, proxies/sandbox/apiproxy/policies/AssignMessage.400InvalidBase64Encoding.xml, proxies/sandbox/apiproxy/policies/AssignMessage.400InvalidTargetIdentifierValue.xml, proxies/sandbox/apiproxy/policies/AssignMessage.404ProxyNotFoundErrorResponse.xml, proxies/sandbox/apiproxy/policies/Javascript.CheckTargets.xml, proxies/sandbox/apiproxy/policies/Python.DecodeBase64.xml, proxies/sandbox/apiproxy/policies/RaiseFault.400MalformedTargetIdentifier.xml, proxies/sandbox/apiproxy/resources/jsc/BarsLibrary.js, proxies/sandbox/apiproxy/resources/jsc/CheckTargets.js, proxies/sandbox/apiproxy/resources/py/DecodeBase64String.py, proxies/sandbox/apiproxy/targets/sandbox.xml, specification/examples/invalid-base64.json, specification/examples/malformed-target-identifier.json, tests/pytest.ini, tests/test_appointment.py, tests/test_endpoints.py, tests/test_target_identifier.py
=> AMB-1325 add extra checks for NHSD_Target_Identifier

specification/booking-and-referral.yaml
Description Text Changes, no functional changes
=> Amb 9990 documentation update

specification/booking-and-referral.yaml
=> AMB000 - AMP 941 API Specs - add Errors section

specification/booking-and-referral.yaml
=> AMB-000 AMP-941 API Specs - add Errors section

specification/booking-and-referral.yaml, specification/schemas/TargetIdentifier.yaml
=> AMB-000 Try this API - update target identifier in spec to be Base64 encoded

README.md, terraform/README.md, tests/README.md
=> AMB-1331 update readme files

azure/azure-release-pipeline.yml
=> AMB-1350 disable _status monitoring for prod

azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml
=> AMB-1350 disable _status monitoring for ptl

manifest_template.yml
=> AMB-000 update prod spike arrest values

manifest_template.yml
=> AMB-000 spike arrest on prod 1000ps

proxies/live/apiproxy/policies/PopulateCache.Targets.xml
=> AMB-000 update cache expiry to 15 mins

specification/booking-and-referral.yaml, specification/examples/metadata/BaRS_API_Capability_Statement.json
=> Amb 9987 capability statement reqs

proxies/live/apiproxy/policies/AssignMessage.AddCapabilityStatement.xml, proxies/sandbox/apiproxy/policies/AssignMessage.AddCapabilityStatement.xml, terraform/Makefile, tests/test_metadata.py
=> AMB-9987 Fix deployment examples

proxies/live/apiproxy/policies/LookupCache.NrlfAccessToken.xml, proxies/live/apiproxy/proxies/default.xml, proxies/live/apiproxy/resources/jsc/NrlfAddAuthorization.js, proxies/live/apiproxy/targets/bref-target.xml, proxies/live/apiproxy/targets/nrlf-consumer-target.xml, tests/test_document_reference.py
=> Fix AMB-1504 - Cache issue

proxies/live/apiproxy/policies/AssignMessage.NrlfRequest.xml, proxies/live/apiproxy/proxies/default.xml, proxies/live/apiproxy/targets/bref-target.xml, proxies/live/apiproxy/targets/nrlf-producer-target.xml, proxies/sandbox/apiproxy/policies/AssignMessage.NrlfRequest.xml, sandbox/src/routes/document_reference.py, specification/examples/document_reference/POST-success.json, specification/examples/document_reference/id/DELETE-success.json, specification/examples/document_reference/id/Not-Found.json, tests/test_document_reference.py
=> Amb 1505 add /document reference/id endpoint

azure/templates/post-deploy.yml, terraform/Makefile, terraform/alb.tf, terraform/alb/alb.tf, terraform/alb/target_group.tf, terraform/alb/variables.tf, terraform/api.tf, terraform/api/logs.tf, terraform/api/variables.tf, terraform/variables.tf
=> AMB-1447 BaRS deploy terraform during pipeline

proxies/live/apiproxy/policies/AssignMessage.403ReceiverMtlsResponse.xml, proxies/live/apiproxy/targets/bref-target.xml, specification/examples/forbidden.json, tests/test_appointment.py, tests/test_document_reference.py
=> AMB-1537 MTLS error handling

specification/booking-and-referral-1.1.0.yaml, specification/booking-and-referral.yaml, specification/examples/message_definition/MessageDefinition_ServiceRequest-request_CaseTransfer.json, specification/examples1.1.0/200_DELETE.json, specification/examples1.1.0/200_PUT.json, specification/examples1.1.0/201_POST.json, specification/examples1.1.0/document_reference/GET-success.json, specification/examples1.1.0/document_reference/id/GET-success.json, specification/examples1.1.0/document_reference/id/PUT-body.json, specification/examples1.1.0/message_definition/MessageDefinition_ServiceRequest-request_CaseTransfer.json
=> Amb 9984 1.1.0 updates

proxies/live/apiproxy/policies/Javascript.setVersion.xml, proxies/live/apiproxy/proxies/default.xml, proxies/live/apiproxy/resources/jsc/SetTargetUrl.js, proxies/live/apiproxy/resources/jsc/SetVersion.js
=> AMB-1600-Investigate-Header-parsing 

README.md, tests/README.md
=> AMB-1341 update readme file

Makefile, manifest_template.yml
=> AMB-1612 publish v1.1.0 spec

.pre-commit-config.yaml, infra/outputs.tf, infra/variables.tf, infra/vpc_link.tf, terraform/alb.tf, terraform/alb/alb.tf, terraform/alb/security_group.tf, terraform/alb/variables.tf, terraform/infra.tf, terraform/mock-receiver.tf, terraform/mock-receiver/service.tf, terraform/mock-receiver/variables.tf
=> Changed vpc_id and lb_subnet_ids to private_subnet_ids

specification/booking-and-referral-1.1.0.yaml, specification/booking-and-referral.yaml
=> Amb 9983 api spec tweaks

proxies/live/apiproxy/resources/jsc/HandleErrors.js, proxies/live/apiproxy/targets/bref-target.xml
=> AMB-1692 update error handling

Makefile
=> AMB-000 publish spec 1.2.0

manifest_template.yml
=> AMB-000 add new spec to manifest file

pyproject.toml
=> AMB-1529 fix github build

.github/workflows/continuous-integration.yml, Makefile, package-lock.json, package.json, pyproject.toml
=> AMB-000 fix github build

specification/booking-and-referral-1.1.0.yaml, specification/booking-and-referral-1.2.0.yaml, specification/booking-and-referral.yaml
=> Amb 99998 suggested changes

proxies/live/apiproxy/policies/PopulateCache.Targets.xml, proxies/live/apiproxy/policies/VerifyAPIKey.CacheRefresh.xml, proxies/live/apiproxy/proxies/default.xml, proxies/live/apiproxy/targets/bref-target.xml
=> AMB-1851 update caching

proxies/live/apiproxy/resources/jsc/ValidateRequest.js, tests/test_endpoints.py
=> Removing suffix validation from ValidateRequest.js

proxies/live/apiproxy/policies/FlowCallout.GetEnvironmentKeyValueMapData.xml, proxies/live/apiproxy/policies/KVM.GetGitHubToken.xml, proxies/live/apiproxy/policies/ServiceCallout.GetTargetsKvm.xml, proxies/live/apiproxy/proxies/default.xml, proxies/live/apiproxy/resources/jsc/BarsLibrary.js, proxies/live/apiproxy/resources/jsc/SetTargetUrl.js, proxies/live/apiproxy/resources/jsc/UnpackVars.js, proxies/live/apiproxy/resources/py/DecodeBase64String.py, proxies/live/apiproxy/targets/bref-target.xml
=> AMB-1851 private repo SC refactor

azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, azure/project.yml, proxies/live/apiproxy/policies/AssignMessage.AddAuthorizationHeaders.xml, proxies/live/apiproxy/policies/RaiseFault.404PageNotFound.xml, proxies/live/apiproxy/policies/RaiseFault.406SendNotAcceptable.xml, proxies/live/apiproxy/proxies/default.xml, proxies/live/apiproxy/resources/jsc/ErrorRepository.js, proxies/live/apiproxy/resources/jsc/HandleErrors.js, proxies/live/apiproxy/targets/bref-aws-target.xml, proxies/live/apiproxy/targets/bref-target.xml, proxies/sandbox/apiproxy/proxies/default.xml, proxies/sandbox/apiproxy/targets/bars-sandbox.xml, specification/booking-and-referral.yaml
=> AMB-2077 Amend BaRS proxy with new endpoints

specification/booking-and-referral-1.1.0.yaml, specification/booking-and-referral-1.2.0.yaml, specification/booking-and-referral.yaml
=> AMB-2909-link-url

proxies/live/apiproxy/policies/AM-S3Request.xml, proxies/live/apiproxy/policies/JC-AWSSignV4.xml, proxies/live/apiproxy/policies/KVM.GetS3Credentials.xml, proxies/live/apiproxy/policies/SC-CallS3.xml
=> changes to take bucket reference from kvm

proxies/live/apiproxy/targets/bref-target.xml
=> AMB-2137-Bars-Intrim-Solution -removed cache condition

infra/cert_storage.tf, terraform/api/truststore.tf
=> AMB-0001-Change-certificate-format

specification/booking-and-referral-1.1.0.yaml, specification/booking-and-referral-1.2.0.yaml, specification/booking-and-referral.yaml
preliminary addition of header
=> Add use-context header

specification/booking-and-referral-1.1.0.yaml, specification/booking-and-referral-1.2.0.yaml
=> AMB-99994 -use case example update

.github/workflows/codeql.yml
=> Create codeql.yml INC0260070

.github/workflows/continuous-integration.yml, specification/booking-and-referral-1.1.0.yaml, specification/booking-and-referral-1.2.0.yaml, specification/booking-and-referral.yaml, specification/schemas/RequestingSoftware.yaml
=> Amb 99992 api corrections

specification/booking-and-referral-1.1.0.yaml, specification/booking-and-referral-1.2.0.yaml, specification/examples1.2.0/appointment/PATCH-body.json, specification/examples1.2.0/appointment/PUT-body.json, specification/examples1.2.0/service_request/PATCH-body.json, specification/examples1.2.0/service_request/PUT-body.json, specification/examples1.2.0/slots/GET-success.json, specification/schemas/TargetIdentifier.yaml, specification/schemas1.1.0/RequestingOrganisation.yaml, specification/schemas1.1.0/RequestingPractitioner.yaml, specification/schemas1.1.0/RequestingSoftware.yaml, specification/schemas1.1.0/TargetIdentifier.yaml, specification/schemas1.2.0/RequestingOrganisation.yaml, specification/schemas1.2.0/RequestingPractitioner.yaml, specification/schemas1.2.0/RequestingSoftware.yaml
=> more fixups to spec

package-lock.json, package.json
upping redoc version so it properly bundles the OAS files.
=> fixing redoc version

sandbox/src/routes/appointment.py
small change to python sandbox
=> change to sandbox to see if it deploys

specification/examples/appointment/GET-success.json, specification/examples/service_request/GET-success.json, specification/examples1.1.0/service_request/GET-success.json, specification/examples1.2.0/service_request/GET-success.json
change to fix sandbox so it returns  better returns appointments and service requests
=> Amb 2418 oas bars fixup

.github/workflows/continuous-integration.yml, sandbox/src/routes/appointment.py, specification/booking-and-referral-1.2.0.yaml, specification/examples/200_PUT.json, specification/examples/201_POST.json, specification/examples/appointment/PATCH-body.json, specification/examples/appointment/POST-success.json, specification/examples/appointment/PUT-body.json
adding PUT PATCH and DELETE to sandbox (appointments only )
=> adding other methods to sandbox

sandbox/src/routes/appointment.py, specification/booking-and-referral-1.1.0.yaml, specification/booking-and-referral-1.2.0.yaml, specification/booking-and-referral.yaml
fix for sandbox
improving descriptions + URL encoding
=> improving descriptions etc

Dockerfile, sandbox/Dockerfile, sandbox/README.md, sandbox/requirements.txt, sandbox/src/routes/document_reference.py
adding a pass though so that requests are sent to NRL sandbox
=> adding DocumentReference pass though

Dockerfile, proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml, sandbox/src/routes/example_loader.py
=> change cors for sandbox

proxies/live/apiproxy/policies/AssignMessage.NrlfRequest.xml, sandbox/src/routes/document_reference.py, specification/booking-and-referral-1.2.0.yaml
=> Amb 2419 sandbox nds

specification/booking-and-referral-1.2.0.yaml
=> remove End User Org header

proxies/live/apiproxy/policies/AssignMessage.NrlfRequest.xml, proxies/sandbox/apiproxy/policies/AssignMessage.NrlfRequest.xml, sandbox/src/routes/document_reference.py
revert previous PR and change sandbox instead
=> sandbox Policy change

sandbox/src/routes/document_reference.py
=> attemt to fix sandbox

proxies/sandbox/apiproxy/resources/jsc/CheckTargets.js, sandbox/src/routes/document_reference.py, specification/booking-and-referral-1.2.0.yaml, specification/schemas1.2.0/TargetIdentifier.yaml
documenting response headers where missing
=> adding response headers hwere missing

sandbox/src/routes/document_reference.py
add more logging to sandbox to try and diagnose issue.
=> adding more logging to sandbox

sandbox/src/routes/document_reference.py, specification/booking-and-referral-1.2.0.yaml, specification/examples/document_reference/DELETE-success.json, specification/examples/document_reference/GET-success.json, specification/examples/document_reference/POST-body.json, specification/examples/document_reference/id/GET-success.json, specification/examples/document_reference/id/PUT-body.json, specification/examples1.1.0/document_reference/POST-success.json, specification/examples1.1.0/document_reference/id/DELETE-success.json, specification/schemas1.2.0/DocumentReference.yaml
redoing the document reference spec and endpoint in sandbox
=> updaing document reference endpoints

proxies/live/apiproxy/proxies/default.xml, proxies/sandbox/apiproxy/proxies/default.xml
should now match 1.1.0 or above for NRL
=> change routing to >= 1.0.0

proxies/live/apiproxy/proxies/default.xml, proxies/sandbox/apiproxy/policies/AssignMessage.NrlfRequest.xml, proxies/sandbox/apiproxy/resources/jsc/SetnRemoveVersion.js, specification/booking-and-referral-1.2.0.yaml
added missing accept/version headers to NRL calls
=> added missing accept/version headers to NRL calls

proxies/live/apiproxy/proxies/default.xml, proxies/sandbox/apiproxy/proxies/default.xml
Change INT back to how it was for now
=> fix for INT

proxies/sandbox/apiproxy/proxies/default.xml, proxies/sandbox/apiproxy/resources/jsc/SetnRemoveVersion.js, specification/examples1.1.0/document_reference/GET-success.json, specification/examples1.1.0/document_reference/POST-body.json, specification/examples1.1.0/document_reference/POST-success.json, specification/examples1.1.0/document_reference/id/GET-success.json, specification/schemas1.2.0/DocumentReference.yaml, specification/schemas1.2.0/DocumentReferenceBundle.yaml
Fix for version number conversion
=> fix for version numbers

proxies/live/apiproxy/proxies/default.xml, proxies/live/apiproxy/resources/jsc/SetnRemoveVersion.js, specification/schemas1.2.0/DocumentReference.yaml, specification/schemas1.2.0/DocumentReferenceBundle.yaml
move new version check to Live (INT will deploy)
added missing array items to schema
=> fix version on Live, fixs for spec

specification/booking-and-referral-1.1.0.yaml, specification/booking-and-referral-1.2.0.yaml
fixing version number for accept headers, used in the `Try` button stuff
=> fixing version numbers used for accept headers

proxies/live/apiproxy/resources/jsc/SetnRemoveVersion.js, proxies/sandbox/apiproxy/resources/jsc/SetnRemoveVersion.js, specification/booking-and-referral-1.2.0.yaml, specification/schemas1.2.0/DocumentReference.yaml
improvement to version check 
fix for document reference schema
improved wording on Post document reference docs
=> improved version match and fix for schema

specification/booking-and-referral-1.1.0.yaml
added use-context back in where needed
=> added use-context on 1.1.0 for writes
